### ISSUE TITLE
Is there an offline version of "Steganography Online"?

### ISSUE THREAD

**Issue by euphorical** [stylesuxx/steganography#10]
Quick question about "Steganography Online" (https://stylesuxx.github.io/steganography/)

Do you offer an offline version of this? In case people want to use the encoder to encode very sensative info, having an offline version available would be great!

Thanks for your time!

**Comment by stylesuxx** [comment]
Well, you can clone the repo and run it locally, but everything is happening on the client anyway, so the online version would be as "save" as the offline version.
